Thulesson08CF/Thulesson08CF/Models/ThuBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Thulesson08CF.Models
{
    /// <summary>
    /// tao cau truc bang Book
    /// </summary>
    public class ThuBook
    {
        [Key]
        public int ThuBookId { get; set; }
        public string ThuTitle { get; set; }
        public string ThuAuthor { get; set; }
        public int ThuYear { get; set;}
        public string ThuPublisher { get; set; }
        public string ThuPicture { get; set; } 
        public int ThuCategoryId { get; set; }

        //thuoc tinh quan he
        public virtual ThuCategory ThuCategory { get; set; }

    }
}

Thulesson08CF/Thulesson08CF/Models/ThuBookStore.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;

namespace Thulesson08CF.Models
{
    public class ThuBookStore : DbContext
    {
        public ThuBookStore() :base("ThuBookStoreConnectionString") { 
        }
        
            //tao cac bang 
        public DbSet<ThuCategory> ThuCategories{ get; set; }
        public DbSet<ThuBook> ThuBooks { get; set; }        
    }
}

Thulesson08CF/Thulesson08CF/Models/ThuCategory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Thulesson08CF.Models
{
    public class ThuCategory
    {
        /// <summary>
        ///tạo cấu trúc bảng dữ liệu
        /// </summary>
        public int CategoryId { get; set; }
        public String CategoryName { get; set; }

        //thuoc tinh quan he
        public virtual ICollection<ThuBook> ThuBooks { get; set; } 

    }
}

Thulesson08CF/Thulesson08CF/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Thulesson08CF.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Trang Đăng ký: ";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Thulesson08CF/Thulesson08CF/Controllers/ThuCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Thulesson08CF.Models;

namespace Thulesson08CF.Controllers
{
    public class ThuCategoryController : Controller
    {
        private static ThuBookStore _ThuBookStore;
        public ThuCategoryController()
        {
            _ThuBookStore = new ThuBookStore();
        }
        // GET: ThuCategory
        public ActionResult Index()
        {
            var ThuCategory=_ThuBookStore.ThuCategories.ToList();
            return View(ThuCategory);
        }
        [HttpGet]
        public ActionResult ThuCreate() {
            var ThuCcategory=new ThuCategory();
            return View(ThuCcategory);
        }
        public ActionResult ThuCreate(ThuCategory thuCategory) {
            _ThuBookStore.ThuCategories.Add(thuCategory);
            _ThuBookStore.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Thulesson08CF/Thulesson08CF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lê  Thương Hoài Thu</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Lê Thương Hoài Thu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Thu:Ds  Category", "Index", "ThuCategory", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lê Thương Hoài Thu</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Thulesson08CF/Thulesson08CF/Views/ThuCategory/Index.cshtml
@model IEnumerable<Thulesson08CF.Models.ThuCategory>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "ThuCreate")
</p>
<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>